### PR TITLE
Controllers Specs

### PR DESCRIPTION
**Pull request by Ogaga01**
# Hello Reviewer 👋 

In this project milestone, I implemented the following requirements:
- Add RSpec as a gem to your project.
- Create a Request spec file for all your controllers.
- Make sure that for each action you check:
    - If the response status was correct.
    - If a correct template was rendered.
    - If the response body includes correct placeholder text.

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @Ogaga01, kindly add the key features to your readme 👍🏿

**Comment by Ogaga01** [comment]
> Hi @Ogaga01, kindly add the key features to your readme 👍🏿

Hi @prolajumokeoni I have added the Key Features to the Readme file

**Comment by Ogaga01** [comment]
> > Hi @Ogaga01, kindly add the key features to your readme 👍🏿
> 
> Hi @prolajumokeoni, I have added the Key Features to the Readme file

@prolajumokeoni I am still waiting for the review

**Comment by prolajumokeoni** [comment]
HI @Ogaga01, when I run rspec spec it says no example
Screenshot_26

**Comment by Ogaga01** [comment]
> HI @Ogaga01, when I run rspec spec it says no example Screenshot_26

@prolajumokeoni You have to run rspec on the individual files. run `rspec spec/requests/users_spec.rb` and `rspec spec/request/posts_spec.rb` 

>

**Review by prolajumokeoni — APPROVED** [review]
Hi @Ogaga01 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- `index` and `show` actions for `User` and `Post` controllers are tested  ✅ 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by prolajumokeoni** [comment]
> > HI @Ogaga01, when I run rspec spec it says no example Screenshot_26
> 
> @prolajumokeoni You have to run rspec on the individual files. run `rspec spec/requests/users_spec.rb` and `rspec spec/request/posts_spec.rb`
> 
> >

everything works welldone

**Pull request merged**
